### ISSUE TITLE
Quick Start Tutorial 

### ISSUE THREAD

**Issue by jspenc72** [JeremyMarshall/angular-fullstack-dist#1]
Hey can you post code snippets on how to get started using this Docker image immediately so we don't have to wait for:

``` bash
yo angular-fullstack:docker

```

to be included in the generator? 

Also, is this image compatible with the latest 4.0.1 version of the generator?

Best,
Jesse

**Comment by stherrienaspnet** [comment]
Hello Jeremy,
I Have a fresh Ubuntu installation 16.04 and i just installed docker to run your Image but i have an error and the container stop to run.
Status: Downloaded newer image for generatorangularfullstack/angular-fullstack-dist:4.1.1
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v7.3.0
npm info lifecycle @4.1.1~prestart: @4.1.1
npm info lifecycle @4.1.1~start: @4.1.1

> @4.1.1 start /usr/src/app
> node server

module.js:472
    throw err;
    ^

Error: Cannot find module '/usr/src/app/server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm info lifecycle @4.1.1~start: Failed to exec start script
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @4.1.1 start: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @4.1.1 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

Best regards,
Stephane
